import { useState } from 'react'
import { Icon, CardHeader, CardTabs, DataTable, Chip, DonutChart, SummaryCard, chartColors, type Column } from '../components'
import {
  RANKING_V2_DATA,
  RANKING_V2_THEME_SCORES,
  type RankingV2Platform,
  type LocationThemeRankRow,
  type LocationThemeRow,
} from '../data/rankingV2ReportData'
import {
  PLATFORM_TABS,
  EmptyPlatformState,
  buildSummaryStats,
  buildUnderstandingStats,
  RANKING_V2_RANK_BY_PLATFORM_COLUMNS,
  RANKING_V2_SIGNAL_COLUMNS,
  RANKING_V2_COMPETITOR_COLUMNS,
  buildCompetitorRows,
  flattenThemeScores,
  buildThemeScoreColumns,
} from './rankingV2Shared'

const RANK_BUCKETS: { key: LocationThemeRow['rankBucket']; label: string; color: string }[] = [
  { key: 'rank1_3', label: 'Themes ranking 1-3', color: chartColors.resolved },
  { key: 'rank4_10', label: 'Themes ranking 4-10', color: chartColors.escalated },
  { key: 'rank10Plus', label: 'Themes ranking 11+', color: chartColors.unresolved },
]

function average(nums: number[]): number {
  if (!nums.length) return 0
  return Math.round(nums.reduce((a, b) => a + b, 0) / nums.length)
}

interface ThemeRankTableRow extends Record<string, unknown> {
  name: string
  avgRank: number
  ChatGPT: number
  Gemini: number
  Perplexity: number
}

export function LocationThemeRankingDetailScreen({
  location,
  onBack,
}: {
  location: LocationThemeRankRow
  onBack: () => void
}) {
  const [platform, setPlatform] = useState<RankingV2Platform>('ChatGPT')
  const [rankAnalysisPlatform, setRankAnalysisPlatform] = useState<RankingV2Platform>('ChatGPT')
  const [signalsPlatform, setSignalsPlatform] = useState<RankingV2Platform>('ChatGPT')
  const [competitorsPlatform, setCompetitorsPlatform] = useState<RankingV2Platform>('ChatGPT')
  const [expandedThemes, setExpandedThemes] = useState<Set<string>>(new Set())

  const chatgptData = RANKING_V2_DATA.ChatGPT!
  const summaryStats = buildSummaryStats()
  const understandingStats = buildUnderstandingStats(chatgptData)

  function toggleTheme(themeName: string) {
    setExpandedThemes((prev) => {
      const next = new Set(prev)
      if (next.has(themeName)) next.delete(themeName)
      else next.add(themeName)
      return next
    })
  }

  const themeScoreRows = flattenThemeScores(RANKING_V2_THEME_SCORES, expandedThemes)
  const themeScoreColumns = buildThemeScoreColumns(expandedThemes, toggleTheme)
  const unverifiedCount = chatgptData.recognizedSignals.filter((s) => s.status !== 'VERIFIED').length
  const competitorRows = buildCompetitorRows(chatgptData)

  const totalThemes = location.themes.length
  const avgRank = average(
    location.themes.flatMap((t) => Object.values(t.ranks).filter((v): v is number => v !== undefined)),
  )

  const donutData = RANK_BUCKETS.map((b) => ({
    name: b.label,
    value: location.themes.filter((t) => t.rankBucket === b.key).length,
    color: b.color,
  })).filter((d) => d.value > 0)

  const themeTableColumns: Column<ThemeRankTableRow>[] = [
    { key: 'name', label: 'Themes' },
    { key: 'avgRank', label: 'Average rank', width: 140 },
    { key: 'ChatGPT', label: 'ChatGPT', width: 120 },
    { key: 'Gemini', label: 'Gemini', width: 120 },
    { key: 'Perplexity', label: 'Perplexity', width: 120 },
  ]

  const themeTableRows: ThemeRankTableRow[] = location.themes.map((t) => ({
    name: t.name,
    avgRank: average(Object.values(t.ranks).filter((v): v is number => v !== undefined)),
    ChatGPT: t.ranks.ChatGPT ?? 0,
    Gemini: t.ranks.Gemini ?? 0,
    Perplexity: t.ranks.Perplexity ?? 0,
  }))

  return (
    <div className="flex flex-1 flex-col min-h-0 min-w-0 overflow-y-auto bg-white">
      <div className="flex h-16 shrink-0 items-center gap-sm px-2xl">
        <button
          type="button"
          aria-label="Back"
          onClick={onBack}
          className="flex size-9 items-center justify-center rounded-sm hover:bg-surface-hover"
        >
          <Icon name="arrow_back" size={20} className="text-text-icon" />
        </button>
        <span className="text-h3 text-text-primary">{location.location}</span>
      </div>

      <div className="flex flex-col gap-xl px-2xl pb-xl">
        {/* Average rank + Understanding your rank */}
        <div className="flex gap-lg">
          <div className="w-[280px] shrink-0">
            <SummaryCard title="Average rank" stats={summaryStats} />
          </div>
          <div className="flex-1 min-w-0">
            <SummaryCard title="Understanding your rank" stats={understandingStats} />
          </div>
        </div>

        {/* What is your rank across AI sites */}
        <div className="rounded-md border border-border bg-surface p-2xl">
          <CardHeader title="What is your rank across AI sites" subtitle="Your ranking position in answers generated by AI sites" />
          <div className="mt-lg">
            <DataTable columns={RANKING_V2_RANK_BY_PLATFORM_COLUMNS} data={chatgptData.rankByPlatform} />
          </div>
        </div>

        {/* What is your ranking analysis */}
        <div className="rounded-md border border-border bg-surface p-2xl">
          <CardHeader title="What is your ranking analysis" subtitle="How AI platforms score and evaluate this location in answers generated by AI sites" />
          <div className="mt-lg mb-lg">
            <CardTabs tabs={PLATFORM_TABS} activeTab={rankAnalysisPlatform} onChange={(id) => setRankAnalysisPlatform(id as RankingV2Platform)} />
          </div>
          {rankAnalysisPlatform === 'ChatGPT' ? (
            <DataTable
              columns={themeScoreColumns}
              data={themeScoreRows}
              autoRowHeight
              rowMenuItems={[
                { label: 'View response', visible: (row) => !row._isHeader, onClick: () => {} },
                { label: 'View citations', visible: (row) => !row._isHeader, onClick: () => {} },
              ]}
            />
          ) : (
            <EmptyPlatformState label="ranking data" />
          )}
        </div>

        {/* What are your top signals that contribute to your ranking */}
        <div className="rounded-md border border-border bg-surface p-2xl">
          <CardHeader title="What are your top signals that contribute to your ranking" subtitle="Signals AI sites detect when your business appears in AI-generated answers" />
          <div className="mt-lg mb-lg">
            <CardTabs tabs={PLATFORM_TABS} activeTab={signalsPlatform} onChange={(id) => setSignalsPlatform(id as RankingV2Platform)} />
          </div>
          {signalsPlatform === 'ChatGPT' ? (
            <>
              <DataTable columns={RANKING_V2_SIGNAL_COLUMNS} data={chatgptData.recognizedSignals} />
              <p className="mt-md text-small text-text-secondary">
                {chatgptData.recognizedSignals.length} signals detected &middot; {unverifiedCount} unverified
              </p>
            </>
          ) : (
            <EmptyPlatformState label="signal data" />
          )}
        </div>

        {/* How are you performing against your competitors */}
        <div className="rounded-md border border-border bg-surface p-2xl">
          <CardHeader title="How are you performing against your competitors" subtitle="Your rank vs. competitors and their top ranking signals" />
          <div className="mt-lg mb-lg">
            <CardTabs tabs={PLATFORM_TABS} activeTab={competitorsPlatform} onChange={(id) => setCompetitorsPlatform(id as RankingV2Platform)} />
          </div>
          {competitorsPlatform === 'ChatGPT' ? (
            <DataTable columns={RANKING_V2_COMPETITOR_COLUMNS} data={competitorRows} autoRowHeight />
          ) : (
            <EmptyPlatformState label="competitor data" />
          )}
        </div>

        <div className="rounded-md border border-border bg-surface p-2xl">
          <CardHeader title="How are you ranking for each theme?" subtitle="Breakdown of themes by their ranking position" />
          <div className="mt-lg mb-lg">
            <CardTabs tabs={PLATFORM_TABS} activeTab={platform} onChange={(id) => setPlatform(id as RankingV2Platform)} />
          </div>
          {platform === 'ChatGPT' ? (
            <div className="flex flex-wrap gap-2xl">
              <div className="flex shrink-0 items-start gap-2xl">
                <div className="flex flex-col gap-xs">
                  <span className="text-h3 text-text-primary">{totalThemes}</span>
                  <span className="text-small text-text-secondary">Themes</span>
                </div>
                <div className="flex flex-col gap-xs">
                  <span className="text-h3 text-text-primary">{avgRank}</span>
                  <span className="text-small text-text-secondary">Average rank</span>
                </div>
              </div>
              <div className="w-[280px] shrink-0">
                <DonutChart data={donutData} />
              </div>
              <div className="flex flex-1 min-w-[280px] flex-col gap-md">
                {RANK_BUCKETS.map((b) => {
                  const themes = location.themes.filter((t) => t.rankBucket === b.key)
                  if (!themes.length) return null
                  return (
                    <div key={b.key} className="flex items-center gap-lg rounded-md border border-border p-lg">
                      <div className="flex w-[140px] shrink-0 flex-col gap-xs">
                        <span className="text-h3 text-text-primary">{themes.length}</span>
                        <span className="flex items-center gap-xs text-small text-text-secondary">
                          <span className="inline-block size-2 rounded-full" style={{ backgroundColor: b.color }} />
                          {b.label}
                        </span>
                      </div>
                      <div className="flex flex-wrap gap-xs">
                        {themes.map((t) => (
                          <Chip key={t.name} label={t.name} variant="neutral" />
                        ))}
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          ) : (
            <div className="flex h-[200px] items-center justify-center rounded-md border border-border bg-surface text-body text-text-secondary">
              No data yet for this AI site.
            </div>
          )}
        </div>

        <div className="rounded-md border border-border bg-surface p-2xl">
          <CardHeader title="How are your themes ranking on ai sites?" subtitle="Breakdown of themes ranking position on ai sites" />
          <div className="mt-lg">
            <DataTable columns={themeTableColumns} data={themeTableRows} />
          </div>
        </div>
      </div>
    </div>
  )
}
